#!/bin/bash -l 
#SBATCH -p debug
#SBATCH -N 1
#SBATCH -t 00:01:00 
#SBATCH -J Blocked_job 
#SBATCH -o MyBlockedOutputFile.%j.out
#SBATCH -e MyBlockedErrorFile.%j.err


srun -n 1 -N 1 ./benchmark-blocked
